import React from 'react'
import Carousel from 'react-bootstrap/Carousel'
import '../sass/componentSass/My_Carousel.scss'


function My_Carousel({ widthCarrousel, heightCarousel }) {
  const arrayImagCarrousel = [
    {
      img: 'microservicesCarousel1.webp',
      text: 'Architecture of microservices with API REST communication'
    },
    {
      img: 'microservicesCarousel2.webp',
      text: 'React + Spring Boot CRUD Full-Stack Application'
    },
    {
      img: 'microservicesCarousel3.webp',
      text: 'Differents architectural approaches'
    },
    {
      img: 'microservicesCarousel4.webp',
      text: 'Microservices and microfrontends transition'
    },
    {
      img: 'microservicesCarousel5.webp',
      text: 'Composite UI generated by microservices'
    },
    {
      img: 'microservicesCarousel6.webp',
      text: "Differents React applications in an architecture of microservices"
    },
    {
      img: 'microservicesCarousel7.webp',
      text: "Example of application with microservices and microfrontends"
    },
    {
      img: 'microservicesCarousel8.webp',
      text: "Example of use of Dockers in microservices aplications"
    },
    {
      img: 'microservicesCarousel9.webp',
      text: 'Modulation in Frontend application:  Micro-Frontends'
    },
    {
      img: 'microservicesCarousel10.webp',
      text: 'Monolitic Application Vs. Modular Application with Microservices'
    }
  ]
  return (
    <Carousel className="contMyCarousel" slide="true" indicators="false" wrap="true" fade="true" interval="3000" width={widthCarrousel} height={heightCarousel}>
      {
        arrayImagCarrousel.map((elem, index) => {
          return (
            <Carousel.Item key={index}>
              <img className="imageCarousel" src={`./src/assets/images/Carrousel/${elem.img}`} alt={`Slide ${index + 1}`} />
              <Carousel.Caption>
                <h3 className="textImageCarousel">{elem.text}</h3>
              </Carousel.Caption>
            </Carousel.Item>
          )
        })
      }
    </Carousel>
  )
}


export default My_Carousel
